### ISSUE TITLE
Subtasks without 'name' field throw exceptions

### ISSUE THREAD

**Issue by lottspot** [lottspot/makeit#2]
A task which generates subtasks which do not specify a 'name' task will raise the following exception

```
Traceback (most recent call last):
  File "/mnt/files/shared/projects/inque-ink/.pyenv/lib/python2.7/site-packages/doit-0.29.0-py2.7.egg/doit/doit_cmd.py", line 168, in run
    return command.parse_execute(args)
  File "/mnt/files/shared/projects/inque-ink/.pyenv/lib/python2.7/site-packages/doit-0.29.0-py2.7.egg/doit/cmd_base.py", line 122, in parse_execute
    return self.execute(params, args)
  File "/mnt/files/shared/projects/inque-ink/.pyenv/lib/python2.7/site-packages/doit-0.29.0-py2.7.egg/doit/cmd_base.py", line 380, in execute
    self, params, args)
  File "build/bdist.linux-x86_64/egg/makeit/loader.py", line 33, in load_tasks
    processed = self._process_makeit_extensions(taskdicts)
  File "build/bdist.linux-x86_64/egg/makeit/loader.py", line 100, in _process_makeit_extensions
    self._makeit_ext_depinject_do(task)
  File "build/bdist.linux-x86_64/egg/makeit/loader.py", line 128, in _makeit_ext_depinject_do
    injected_deps = self._injections.get(task['name'], [])
KeyError: 'name'
```

**Comment by lottspot** [comment]
This seems like poor behavior, but doit may actually handle this condition in same or similar fashion. Makeit should model it's behavior in this situation as closely to doit's behavior as it reasonably can.
